name: Fetch AWS Resources with Github
on:
  push:
    branches:
      - feature/test  # Trigger on push to the main branch
jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Aws PowerShell Module
        shell: pwsh
        run: |
          Install-Module -Name AwsPowershell -Force -Scope CurrentUser
          Import-Module -Name AwsPowershell -Force

      - name: AWS Login using PowerShell and Deploy the Report
        shell: pwsh
        run: |
          $accesskey = "${{ secrets.AWS_ACCESS_KEY }}"
          $secretkey = "${{ secrets.AWS_SECRET_KEY }}"
          Set-AWSCredential -AccessKey $accesskey -SecretKey $secretkey
          Initialize-AWSDefaultConfiguration -Region "us-east-2"
          ./scripts/s3-report.ps1

        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
 
    
